### ISSUE TITLE
Add support for Angular Storybook

### ISSUE THREAD

**Issue by jogelin** [NicholasBoll/cypress-storybook#19]
I am trying to setup this lib on my project:

- Nrwl/NX monorepo
- Angular components
- Storybook 6

But I have this error when I included the react.js into my preview.js:
`Module not found: Error: Can't resolve '@storybook/react' in '/Users/Jgelin/dev/grizzly/node_modules/cypress-storybook'`

**Comment by NicholasBoll** [comment]
So far this package only supports react. Other frameworks could be supported by adding framework adapters (`react.js` is the adapter for React). You're getting this error because the React adapter requires `@storybook/react` and you probably don't have that as a dependency because you're probably using `@storybook/angular` instead.

There isn't much code in https://github.com/NicholasBoll/cypress-storybook/blob/master/react.js. There's framework specific code there that forces a Story to load (or reload) properly without a new page refresh. There's some framework agnostic code as well that could be abstracted into a common file.

I'm interested in supporting other frameworks like Angular and Vue, but an adapter hasn't been made yet. I'm open to a pull request to add support. If you're not comfortable doing so, I'm sure I'll get around to an Angular adapter at some point. I'll leave this issue open and change the title to "Add support for Angular"

**Comment by NicholasBoll** [comment]
Fixed in https://github.com/NicholasBoll/cypress-storybook/releases/tag/v0.5.0
