### ISSUE TITLE
win.__setCurrentStory is not a function

### ISSUE THREAD

**Issue by marseam** [NicholasBoll/cypress-storybook#39]
I have followed the guide and getting

![image](https://user-images.githubusercontent.com/2734403/138683428-fc2e9ed0-1bb4-4a96-8bc3-0a496b496f9c.png)

using 
"cypress": "^8.6.0",
 "cypress-storybook": "^0.5.1",

storybook 6.*
node 14.x

i've added 
import 'cypress-storybook/cypress'; to the support files and using the code followed in teh guide, any idea?

**Comment by redbugz** [comment]
We already have that import in our preview.js, and this error comes up seemingly randomly about 3-5% of our builds

**Comment by michaelvoase** [comment]
I know this issue is closed but @redbugz did you get any resolution. I have just tried using this and I have the import (mine is the Angular import) within my preview.js and I still get the error that this issue mentions. 

As a bit of transparency I'm using Angular 15 and an NX project, its going to be really valuable to allow us to set our own stories on the fly if we can get around this issue.
